### ISSUE TITLE
Implement functionality to upload a users repository credentials

### ISSUE THREAD

**Issue by npch** [softwaresaved/software-assessment-framework#11]
Allow a user to upload their GitHub or BitBucket tokens for use, and delete them after use.

**Comment by js-robinson** [comment]
Can you clarify the use-case here?  Is to access private repositories, or to overcome API rate limits?

**Comment by js-robinson** [comment]
Fixed in 2821ebb1f761950b57ac38e3d5257a3344ad3f06
