### ISSUE TITLE
Implement metric to identify presence of README file

### ISSUE THREAD

**Issue by npch** [softwaresaved/software-assessment-framework#4]
Does the repository have one of the following:

- README
- README.txt
- README.md
- README.html

in the root of the repository.

Should probably score as binary i.e. 1.0 if present, 0.0 if not.

**Comment by js-robinson** [comment]
Implemented in 6f6d6b71083f1ca62a58fcadc0f212f9e7dfee41
Scores 0 if none of the listed file names is present
Scores 100 is present and has non-zero length content
