### ISSUE TITLE
Implement metric to identify presence of LICENSE file

### ISSUE THREAD

**Issue by npch** [softwaresaved/software-assessment-framework#5]
Does the repository have one of the following:

LICENSE
LICENSE.txt
LICENSE.md
LICENSE.html
LICENCE
LICENCE.txt
LICENCE.md
LICENCE.html
in the root of the repository.

Should probably score as binary i.e. 1.0 if present, 0.0 if not.

**Comment by js-robinson** [comment]
Implemented in 6f6d6b71083f1ca62a58fcadc0f212f9e7dfee41
Scores 0 if none of the listed file names is present
Scores 50 if present, but not identifiable
Scores 100 if present and contents are identifiable as one of LGPL, GPL, MIT, BSD, Apache 1.0/1.1/2.0
