### ISSUE TITLE
Implement a "user inputted" interface for a category of metrics

### ISSUE THREAD

**Issue by npch** [softwaresaved/software-assessment-framework#8]
These might include:

- Adequate user documentation
- Adequate developer documentation
- Test data available

This should allow different types of metrics for example:
- binary (e.g. documentation is there or it's not)
- Likert scale (e.g. the documentation is useful: strongly disagree / disagree / neither agree nor disagree / agree / strongly agree)
- bracketed (e.g. no documentation / minimal installation documentation / substantial documentation)

**Comment by js-robinson** [comment]
UI component now implemented.
Integration of weighting to score processing in progress.

**Comment by js-robinson** [comment]
Resolved in cf1d3ccbca8258738dc91258da2b61214a6809dc
